package com.yiche.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2018-06-12T14:41:00.648+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "LoginService", 
                  wsdlLocation = "https://oapi.bitauto.com/hrservices/login.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class LoginService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "LoginService");
    public final static QName LoginServiceSoap12 = new QName("http://tempuri.org/", "LoginServiceSoap12");
    public final static QName LoginServiceSoap = new QName("http://tempuri.org/", "LoginServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://oapi.bitauto.com/hrservices/login.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LoginService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://oapi.bitauto.com/hrservices/login.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LoginService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LoginService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LoginService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LoginService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LoginService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns LoginServiceSoap
     */
    @WebEndpoint(name = "LoginServiceSoap12")
    public LoginServiceSoap getLoginServiceSoap12() {
        return super.getPort(LoginServiceSoap12, LoginServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginServiceSoap
     */
    @WebEndpoint(name = "LoginServiceSoap12")
    public LoginServiceSoap getLoginServiceSoap12(WebServiceFeature... features) {
        return super.getPort(LoginServiceSoap12, LoginServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns LoginServiceSoap
     */
    @WebEndpoint(name = "LoginServiceSoap")
    public LoginServiceSoap getLoginServiceSoap() {
        return super.getPort(LoginServiceSoap, LoginServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginServiceSoap
     */
    @WebEndpoint(name = "LoginServiceSoap")
    public LoginServiceSoap getLoginServiceSoap(WebServiceFeature... features) {
        return super.getPort(LoginServiceSoap, LoginServiceSoap.class, features);
    }

}
