package com.yiche.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2018-06-12T14:41:00.517+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "LoginServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface LoginServiceSoap {

    /**
     * 域账号登录认证
     */
    @WebMethod(operationName = "Login", action = "http://tempuri.org/Login")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginResponse")
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    public LoginResult login(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    /**
     * 根据域账号获取员工信息
     */
    @WebMethod(operationName = "GetEmployeeByDomainAccount", action = "http://tempuri.org/GetEmployeeByDomainAccount")
    @RequestWrapper(localName = "GetEmployeeByDomainAccount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmployeeByDomainAccount")
    @ResponseWrapper(localName = "GetEmployeeByDomainAccountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmployeeByDomainAccountResponse")
    @WebResult(name = "GetEmployeeByDomainAccountResult", targetNamespace = "http://tempuri.org/")
    public Employee getEmployeeByDomainAccount(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        java.lang.String username
    );
}
